# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='owner',
            new_name='user',
        ),
    ]
